### ISSUE TITLE
Satpy NWCSAF reader has very strict file name syntax requirement

### ISSUE THREAD

**Issue by hkocak** [pytroll/pytroll#6]
Dear developers, we apply parallax correction to our NWCSAF products and the end products have "PLAX" suffix at the end of their file name. However Satpy NWCSAF reader does not read those files with names ending with PLAX suffix. Looks like it has a very strict file name requirement which needs to be fixed. Thank you and best regards.

**Comment by djhoese** [comment]
Sorry it seems we didn't see this. The repository you are looking for is https://github.com/pytroll/satpy/. If you are still having issues with this please file a bug there.

**Comment by hkocak** [comment]
Thank you very much
Regards

Hakan


David Hoese <notifications@github.com>, 1 Haz 2020 Pzt, 16:34 tarihinde
şunu yazdı:
